<?php
if (($avicenna_slider_sc = avicenna_get_theme_option('front_page_title_shortcode')) != '' && strpos($avicenna_slider_sc, '[')!==false && strpos($avicenna_slider_sc, ']')!==false) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider"><?php
		// Add anchor
		$avicenna_anchor_icon = avicenna_get_theme_option('front_page_title_anchor_icon');	
		$avicenna_anchor_text = avicenna_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($avicenna_anchor_icon) || !empty($avicenna_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($avicenna_anchor_icon) ? ' icon="'.esc_attr($avicenna_anchor_icon).'"' : '')
											. (!empty($avicenna_anchor_text) ? ' title="'.esc_attr($avicenna_anchor_text).'"' : '')
											. ']');
		}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode($avicenna_slider_sc);
	?></div><?php

} else {

	?><div class="front_page_section front_page_section_title<?php
				$avicenna_scheme = avicenna_get_theme_option('front_page_title_scheme');
				if (!avicenna_is_inherit($avicenna_scheme)) echo ' scheme_'.esc_attr($avicenna_scheme);
				echo ' front_page_section_paddings_'.esc_attr(avicenna_get_theme_option('front_page_title_paddings'));
			?>"<?php
			$avicenna_css = '';
			$avicenna_bg_image = avicenna_get_theme_option('front_page_title_bg_image');
			if (!empty($avicenna_bg_image)) 
				$avicenna_css .= 'background-image: url('.esc_url(avicenna_get_attachment_url($avicenna_bg_image)).');';
			if (!empty($avicenna_css))
				echo ' style="' . esc_attr($avicenna_css) . '"';
	?>><?php
		// Add anchor
		$avicenna_anchor_icon = avicenna_get_theme_option('front_page_title_anchor_icon');	
		$avicenna_anchor_text = avicenna_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($avicenna_anchor_icon) || !empty($avicenna_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($avicenna_anchor_icon) ? ' icon="'.esc_attr($avicenna_anchor_icon).'"' : '')
											. (!empty($avicenna_anchor_text) ? ' title="'.esc_attr($avicenna_anchor_text).'"' : '')
											. ']');
		}
		?>
		<div class="front_page_section_inner front_page_section_title_inner<?php
			if (avicenna_get_theme_option('front_page_title_fullheight'))
				echo ' avicenna-full-height sc_layouts_flex sc_layouts_columns_middle';
			?>"<?php
				$avicenna_css = '';
				$avicenna_bg_mask = avicenna_get_theme_option('front_page_title_bg_mask');
				$avicenna_bg_color = avicenna_get_theme_option('front_page_title_bg_color');
				if (!empty($avicenna_bg_color) && $avicenna_bg_mask > 0)
					$avicenna_css .= 'background-color: '.esc_attr($avicenna_bg_mask==1
																		? $avicenna_bg_color
																		: avicenna_hex2rgba($avicenna_bg_color, $avicenna_bg_mask)
																	).';';
				if (!empty($avicenna_css))
					echo ' style="' . esc_attr($avicenna_css) . '"';
		?>>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$avicenna_caption = avicenna_get_theme_option('front_page_title_caption');
				if (!empty($avicenna_caption) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo !empty($avicenna_caption) ? 'filled' : 'empty'; ?>"><?php echo wp_kses_post($avicenna_caption); ?></h1><?php
				}
			
				// Description (text)
				$avicenna_description = avicenna_get_theme_option('front_page_title_description');
				if (!empty($avicenna_description) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo !empty($avicenna_description) ? 'filled' : 'empty'; ?>"><?php echo wp_kses_post(wpautop($avicenna_description)); ?></div><?php
				}
				
				// Buttons
				if (avicenna_get_theme_option('front_page_title_button1_link')!='' || avicenna_get_theme_option('front_page_title_button2_link')!='') {
					?><div class="front_page_section_buttons front_page_section_title_buttons"><?php
						avicenna_show_layout(avicenna_customizer_partial_refresh_front_page_title_button1_link());
						avicenna_show_layout(avicenna_customizer_partial_refresh_front_page_title_button2_link());
					?></div><?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}